### ISSUE TITLE
Is on_the_spot compatible with Rails 4.x?

### ISSUE THREAD

**Issue by cmendla** [nathanvda/on_the_spot#54]
I tried to install this gem on a rails 4.x installation.

My first question is "Is this Rails 4.0 compatible? "

 I see the field and it has a goldish highlight when I click. However I cannot edit. I had a similar issue when I tried Best_in_place. 

My Rails setup is 

```
Ruby Information    ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]
Rails Version   4.2.7.1
Rails Environment   development ( development/test/production)
```

I have the gem installed and two yml files were created when I ran the installer. 

I added `//= require on_the_spot` to application.js and   `<%= stylesheet_link_tag :on_the_spot %>` to application.html.erb

I added the can_edit in the controller

```
Class FailedLoginsController < ApplicationController
  before_action :set_failed_login, only: [:show, :edit, :update, :destroy]

  can_edit_on_the_spot


```

I also ran bundle install and Rake Assets Precomplile

I have `<%= on_the_spot_edit failed_login, :login %> ` in my index.html.erb file. 

Again, the field is there and gets highlighted on mouse-over. However, a click on the field does not allow me to edit. 

Thanks, 

chris

**Comment by nathanvda** [comment]
Yep, I use it in rails 4.2.x and turbolinks 5. 

Which version of the gem and turbolinks are you using? 

So, if click is not doing anything, it looks like a js problem, so things to check (I have no idea of your level of expertise, so this is not ment to be condescending just complete):

* did you include the `application.js` file in the head of your html
* do you get errors in the javascript console in your browser when loading the page (errors in js block further execution)

Did you add the routes as well?

**Comment by cmendla** [comment]
Thanks for the reply. Knowing that it works with rails 4.x is extremely helpful. It is working now. 

Your suggestion to look at the JS console was the key. 

I was using outdated versions of jquery,  

My current Versions : 
  Using on_the_spot 1.0.5
  Using jquery-turbolinks 2.1.0
  Using jquery-ui-rails 6.0.1
  Using rails 4.2.7.1

I changed the jquery links in my application.html.erb to include 

```
<% javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" %>

<% javascript_include_tag "http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"
      integrity="sha256-xNjb53/rY+WmG+4L6tTl9m6PpqknWZvRt0rO1SRnJzw="
      crossorigin="anonymous"%>

  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

  <%= stylesheet_link_tag :on_the_spot %>
```


I'm not sure if the jquery links are optimal or not but it appears that everything Jquery related in the app is working OK. 

Thanks again for the quick response. on_the_spot is now working fine with my Rails 4.x app. 

chris
