### ISSUE TITLE
AssetNotPrecompiled

### ISSUE THREAD

**Issue by TeamRainless** [nathanvda/on_the_spot#58]
Followed the directions exactly for Rails 3/4/5... 

Text gets highlighted Yellow on mouseover... but no way to edit the text after clicking.

They both give the error:

```
<%= stylesheet_link_tag :on_the_spot %>
<%= javascript_include_tag :on_the_spot %>

```

I have included them in the application.js and the application.scss

application.scss
 *= require_tree .
 *= require_self
 *= require on_the_spot

applicaiton.js
//= require on_the_spot

Also ran rails g on_the_spot:install.

Ran rails assets:clean and then rails assets:precompile

Nothing will work.

**Comment by TeamRainless** [comment]
Also receiving the error:

```
Uncaught TypeError: el.editable is not a function

 el.editable(data_url, options);
```

**Comment by TeamRainless** [comment]
Figured it out.  Needed to add on_the_spot into the asset pipeline:

`config/initializers/assets.rb`

Had to put **on_the_spot.js** and **on_the_spot.css** in there like so:

`Rails.application.config.assets.precompile += %w( on_the_spot.js on_the_spot.css)`

Once I did that it worked fine. Should probably add this to the Readme...

**Comment by nathanvda** [comment]
So which rails version are you using? Because 3/4/5 is a bit vague.

**Comment by TeamRainless** [comment]
Well now... to be fair... it's EXTREMELY vague! hahahaha 😄 

Rails 5.2.4.1.  I had it written up there originally but my cat must've been walking the keyboard.
